### ISSUE TITLE
Error when running addon

### ISSUE THREAD

**Issue by bartolomesoriano** [kodi-community-addons/script.artwork.downloader#1]
@Angelinas1 , I am trying this addon in Matrix (Kodi 19.1 64bit, Windows 10), and get this error when running it from Program Addons:

2021-05-24 11:42:21.581 T:8984     INFO <general>: Artwork Downloader: ######## Artwork Downloader: Initializing...............................
2021-05-24 11:42:21.581 T:8984     INFO <general>: Artwork Downloader: ## Add-on Name = Artwork Downloader
2021-05-24 11:42:21.581 T:8984     INFO <general>: Artwork Downloader: ## Version     = 19.0.2
2021-05-24 11:42:31.958 T:8984    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: a bytes-like object is required, not 'str'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\bsori\AppData\Roaming\Kodi\addons\script.artwork.downloader\default.py", line 820, in <module>
                                                       Main()
                                                     File "C:\Users\bsori\AppData\Roaming\Kodi\addons\script.artwork.downloader\default.py", line 138, in __init__
                                                       mediaList = media_listing(startup['mediatype'])
                                                     File "C:\Users\bsori\AppData\Roaming\Kodi\addons\script.artwork.downloader\lib\media_setup.py", line 150, in _media_listing
                                                       imdbnumber = tmdb._search_movie(item.get('label',''),item.get('year',''))
                                                     File "C:\Users\bsori\AppData\Roaming\Kodi\addons\script.artwork.downloader\lib\provider\tmdb.py", line 170, in _search_movie
                                                       medianame = medianame.replace( char , '+' ).replace( '++', '+' ).replace( '+++', '+' )
                                                   TypeError: a bytes-like object is required, not 'str'
                                                   -->End of Python script error report<--

Please let me know if you need a debug log.  Thanks.

**Comment by Angelinas1** [comment]
@bartolomesoriano 

Can you write what is name (Title) for Movie.I suspect that have some special character in name.
illegal_char = ' -<>:"/\|?*%'

**Comment by bartolomesoriano** [comment]
@Angelinas1 , I do not know, since I started the addon from Program Addons.  If I provide you with a debug log will the name of the movie be there?

**Comment by Angelinas1** [comment]
For Log, Need to enable 'Debug' in addon settings.
Then start from Program Addons.

if you have a large collection the search will take a long time.
Better try to read last "downloadreport.txt" in ...Kodi\userdata\addon_data\script.artwork.downloader\

**Comment by bartolomesoriano** [comment]
@Angelinas1 , the addon did not get to create a downloadreport.txt.  I enabled debug in the addon settings and debug logging in Kodi, and you are correct, the movie where it is stopping has special characters: "Céline and Julie Go Boating".  Is this something you can fix? I have a lot of movies with accented characters in the title.

**Comment by Angelinas1** [comment]
I just try same movie from DialogContextMenu   manage... ADM: Get Art solo mode...
And working without error.
[B]Artwork Downloader:[/B]
 - Time of finish: 24 May 2021 - 22:46
[B]Downloaded:[/B]
 - Total Artwork: 9
 - Poster: 1
 - KeyArt: 1
 - Fanart: 1
 - Extrafanart: 3
 - Extrathumbs: 3
[B]Failed items:[/B]
 - [C鬩ne et Julie vont en bateau: Phantom Ladies Over Paris] banner not found!
 - [C鬩ne et Julie vont en bateau: Phantom Ladies Over Paris] clearart not found!
 - [C鬩ne et Julie vont en bateau: Phantom Ladies Over Paris] clearlogo not found!
 - [C鬩ne et Julie vont en bateau: Phantom Ladies Over Paris] discart not found!
 - [C鬩ne et Julie vont en bateau: Phantom Ladies Over Paris] landscape not found!

![screenshot00138](https://user-images.githubusercontent.com/7657140/119406021-75357300-bce2-11eb-97cf-0b736bfad0e0.png)

**Comment by bartolomesoriano** [comment]
@Angelinas1 , this is the report I get from running it with just that movie in solo mode:

[B]Artwork Downloader:[/B]
 - Time of finish: 24 May 2021 - 17:08
[B]Downloaded:[/B]
 - Total Artwork: 0
[B]Failed items:[/B]
 - [Céline and Julie Go Boating] ID not found!
 - [Céline and Julie Go Boating] banner not found!
 - [Céline and Julie Go Boating] clearart not found!
 - [Céline and Julie Go Boating] clearlogo not found!
 - [Céline and Julie Go Boating] discart not found!

I have enabled "Use Local Files" in the addon settings, since I do not want the addon to overwrite the artwork I already have.

I am not running the addon for just one movie, though,  I want to run it against my complete collection, to get any artwork that I am missing.

**Comment by Angelinas1** [comment]
_search_movie starts when "No valid imdbnumber found"
Are you scrape your movie with TMDB or UMS ?
Mine Library was scrape with UMS and have valid imdbnumber ..._search_movie didnt start to look in tmdb.
Please scrape only this movie with ums and start AD again.

**Comment by bartolomesoriano** [comment]
@Angelinas1 , to be clear then, the movies need to have a valid imdbnumber for AD to work?

**Comment by Angelinas1** [comment]
yes :)
Just try scrape with tmdb and have same log like you....didnt try to search all collection .
[B]Artwork Downloader:[/B]
 - Time of finish: 24 May 2021 - 23:17
[B]Downloaded:[/B]
 - Total Artwork: 0
[B]Failed items:[/B]
 - [Céline and Julie Go Boating] banner not found!
 - [Céline and Julie Go Boating] clearart not found!
 - [Céline and Julie Go Boating] clearlogo not found!
 - [Céline and Julie Go Boating] discart not found!
 - [Céline and Julie Go Boating] landscape not found!

**Comment by bartolomesoriano** [comment]
@Angelinas1 , the only scraper I use is the local files one (NFO).  I use Tinymediamanager to get all of the metadata and artwork, and the create the NFOs.  I redid the movie with tmm, and refreshed it in Kodi, and made sure it had a valid imdbnumber.

Tried again and now there is no ID not found in the AD log.  I thought all of my movies had a valid imdbnumber, but I guess there are many that do not.  I will have to go through slowly and fix this, since my collection is about 8300 movies.  Thanks for your help.

**Comment by Angelinas1** [comment]
Tnx Bart...
In future I will try to remove-ignore special character, to avoid this error.
